# Generated by Django 2.1 on 2018-09-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOIQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.DOIQuery')),
            ],
        ),
    ]
