# Generated by Django 2.1 on 2018-09-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfoJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISSN', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='emailinfojournal',
            name='Citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.JournalQuery'),
        ),
    ]
