# Generated by Django 2.1 on 2018-09-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20180907_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinfojournal',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='emailinfojournal',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='emailinfojournal',
            name='title',
        ),
    ]
