# Generated by Django 2.1 on 2018-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20180907_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalquery',
            name='title',
        ),
        migrations.AddField(
            model_name='emailinfojournal',
            name='Author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailinfojournal',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailinfojournal',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
